### ISSUE TITLE
There's no instructions on how to compile or run the project

### ISSUE THREAD

**Issue by cjames9001** [T1mmos/cards2.0#35]
I'd love to try this project out, however I don't see any information on how to run or compile your project.

**Comment by T1mmos** [comment]
Hi, 

I'm back after 3 years :)

I did some work to support a decent Maven build pipeline for the framework and the two plugins, and added the build and run steps to the README. 

Please note that in order to make the games work (compile, runtime) I had to remove a dependency, WebLookAndFeel, and the UI is visually broken, which is something I'm working at. Once the master branch is repaired I will use feature branches to not break anything. Clearly I abused the master branch and left it in a unacceptable state back in 2021.

**Comment by T1mmos** [comment]
Hi again,

Visual fixes have been pushed. FlatLaf is now used instead of WebLaf. Also there is a release made so you can just install the game, no need to build anything.

**Comment by T1mmos** [comment]
There are build instructions now, and even a release build including an installer, so I'm closing this issue.
